baseURL = 'https://alg4.ikesnowy.com/'
languageCode = 'zh-Hans'
title = '《算法（第四版）》C# 题解'
theme = 'hugo-book-modified'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  hardWraps = true

[params]
  BookTheme = 'auto'
  BookToc=false
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = '*'
  BookComments = false
  BookDateFormat = '2006-1-2'
  BookRepo = 'https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp/'
  BookCommitPath = 'commit'